const seriesData = [
    { "codigo": 25436, "descricao": "Taxa média mensal de juros - Total" },
    { "codigo": 27641, "descricao": "Taxa média mensal de juros não rotativo - Total" },
    { "codigo": 25437, "descricao": "Taxa média mensal de juros - Pessoas jurídicas - Total" },
    { "codigo": 27642, "descricao": "Taxa média mensal de juros não rotativo - Pessoas jurídicas - Total" },
    { "codigo": 25438, "descricao": "Taxa média mensal de juros - Pessoas jurídicas - Desconto de duplicatas e recebíveis" },
    { "codigo": 25439, "descricao": "Taxa média mensal de juros - Pessoas jurídicas - Desconto de cheques" },
    { "codigo": 25440, "descricao": "Taxa média mensal de juros - Pessoas jurídicas - Antecipação de faturas de cartão de crédito" },
    { "codigo": 25441, "descricao": "Taxa média mensal de juros - Pessoas jurídicas - Capital de giro com prazo de até 365 dias" },
    { "codigo": 25442, "descricao": "Taxa média mensal de juros - Pessoas jurídicas - Capital de giro com prazo superior a 365 dias" },
    { "codigo": 25443, "descricao": "Taxa média mensal de juros - Pessoas jurídicas - Capital de giro rotativo" },
    { "codigo": 25444, "descricao": "Taxa média mensal de juros - Pessoas jurídicas - Capital de giro total" },
    { "codigo": 25445, "descricao": "Taxa média mensal de juros - Pessoas jurídicas - Conta garantida" },
    { "codigo": 25446, "descricao": "Taxa média mensal de juros - Pessoas jurídicas - Cheque especial" },
    { "codigo": 25447, "descricao": "Taxa média mensal de juros - Pessoas jurídicas - Aquisição de veículos" },
    { "codigo": 25448, "descricao": "Taxa média mensal de juros - Pessoas jurídicas - Aquisição de outros bens" },
    { "codigo": 25449, "descricao": "Taxa média mensal de juros - Pessoas jurídicas - Aquisição de bens total" },
    { "codigo": 25450, "descricao": "Taxa média mensal de juros - Pessoas jurídicas - Arrendamento mercantil de veículos" },
    { "codigo": 25451, "descricao": "Taxa média mensal de juros - Pessoas jurídicas - Arrendamento mercantil de outros bens" },
    { "codigo": 25452, "descricao": "Taxa média mensal de juros - Pessoas jurídicas - Arrendamento mercantil total" },
    { "codigo": 25453, "descricao": "Taxa média mensal de juros - Pessoas jurídicas - Vendor" },
    { "codigo": 25454, "descricao": "Taxa média mensal de juros - Pessoas jurídicas - Compror" },
    { "codigo": 25455, "descricao": "Taxa média mensal de juros - Pessoas jurídicas - Cartão de crédito rotativo" },
    { "codigo": 25456, "descricao": "Taxa média mensal de juros - Pessoas jurídicas - Cartão de crédito parcelado" },
    { "codigo": 25457, "descricao": "Taxa média mensal de juros - Pessoas jurídicas - Cartão de crédito total" },
    { "codigo": 25458, "descricao": "Taxa média mensal de juros - Pessoas jurídicas - Adiantamento sobre contratos de câmbio (ACC)" },
    { "codigo": 25459, "descricao": "Taxa média mensal de juros - Pessoas jurídicas - Financiamento a importações" },
    { "codigo": 25460, "descricao": "Taxa média mensal de juros - Pessoas jurídicas - Financiamento a exportações" },
    { "codigo": 25461, "descricao": "Taxa média mensal de juros - Pessoas jurídicas - Repasse externo" },
    { "codigo": 25462, "descricao": "Taxa média mensal de juros - Pessoas físicas - Total" },
    { "codigo": 27643, "descricao": "Taxa média mensal de juros não rotativo - Pessoas físicas - Total" },
    { "codigo": 25463, "descricao": "Taxa média mensal de juros - Pessoas físicas - Cheque especial" },
    { "codigo": 25464, "descricao": "Taxa média mensal de juros - Pessoas físicas - Crédito pessoal não consignado" },
    { "codigo": 25465, "descricao": "Taxa média mensal de juros - Pessoas físicas - Crédito pessoal não consignado vinculado à composição de dívidas" },
    { "codigo": 25466, "descricao": "Taxa média mensal de juros - Pessoas físicas - Crédito pessoal consignado para trabalhadores do setor privado" },
    { "codigo": 25467, "descricao": "Taxa média mensal de juros - Pessoas físicas - Crédito pessoal consignado para trabalhadores do setor público" },
    { "codigo": 25468, "descricao": "Taxa média mensal de juros - Pessoas físicas - Crédito pessoal consignado para aposentados e pensionistas do INSS" },
    { "codigo": 25469, "descricao": "Taxa média mensal de juros - Pessoas físicas - Crédito pessoal consignado total" },
    { "codigo": 25470, "descricao": "Taxa média mensal de juros - Pessoas físicas - Crédito pessoal total" },
    { "codigo": 25471, "descricao": "Taxa média mensal de juros - Pessoas físicas - Aquisição de veículos" },
    { "codigo": 25472, "descricao": "Taxa média mensal de juros - Pessoas físicas - Aquisição de outros bens" },
    { "codigo": 25473, "descricao": "Taxa média mensal de juros - Pessoas físicas - Aquisição de bens total" },
    { "codigo": 25474, "descricao": "Taxa média mensal de juros - Pessoas físicas - Arrendamento mercantil de veículos" },
    { "codigo": 25475, "descricao": "Taxa média mensal de juros - Pessoas físicas - Arrendamento mercantil de outros bens" }
]

export default seriesData;
